#!/bin/bash
#
# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

DEVICE=a8xelte
VENDOR=samsung
DEVICE_ROOT=vendor/$VENDOR/$DEVICE

echo "Generating vendor makefiles for $DEVICE..."

# Generate a8xelte-vendor.mk
cat > "$DEVICE_ROOT/$DEVICE-vendor.mk" << 'VENDOR_MK'
# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

# Proprietary blobs for a8xelte
# This file is auto-generated by setup-makefiles.sh

$(call inherit-product-if-exists, vendor/samsung/universal7420-common/universal7420-common-vendor.mk)
VENDOR_MK

# Generate BoardConfigVendor.mk
cat > "$DEVICE_ROOT/BoardConfigVendor.mk" << 'BOARDVENDOR_MK'
# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

# BoardConfigVendor for a8xelte
# This file is auto-generated by setup-makefiles.sh
BOARDVENDOR_MK

echo "Done! Generated:"
echo "  $DEVICE_ROOT/$DEVICE-vendor.mk"
echo "  $DEVICE_ROOT/BoardConfigVendor.mk"
